name: CI/CD pipeline

on:
  workflow_dispatch:
    input:
      environment:
        description: This is the environment value where this workflow runs
        default: 'dev'
        requried: true
        type: choice
        options:
          - dev
          - prod
          - staging


jobs:
  
  code:

    runs-on: ubuntu-latest
    steps:
      - name: Check the Code
        run: echo "Check for the code"

  build:
    
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build the docker image
        run: echo "Build the docker image"

  test:
    
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test the pipeline
        run: echo "Testing the piple if works properly"

  deploy:

    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the project
        run: echo "Deploy the pipeline"



    
