name: Hello 

on:
  workflow_dispatch: 


jobs:

  greet:

    runs-on: ubuntu-latest
    steps:

      - name: Say hello to user
        run: echo "Hello Friends"

      - name: Say hello to user
        run: echo "Hello $USER"
  
  detials:
    
    runs-on: ubuntu-latest
    steps:
      
      - name: what is version of python and docker
        run: docker --version && python --version



